ALTER TABLE trips ADD COLUMN baby_seat BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE trips ADD COLUMN more_than_four_passengers BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE trips ADD COLUMN has_pet BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE trips ADD COLUMN special_comments VARCHAR(300);
ALTER TABLE trips ADD COLUMN dispatch_attempts INT NOT NULL DEFAULT 0;
